services:
  web:
    image: githubyumao/mcsmanager-web:latest
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/mcs/web/data:/opt/mcsmanager/web/data
      - /opt/docker/mcs/web/logs:/opt/mcsmanager/web/logs

  daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    ports:
      - "24444:24444"
      - "19565:19565"
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=/opt/docker/mcs/daemon/data/InstanceData
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/mcs/daemon/data:/opt/mcsmanager/daemon/data
      - /opt/docker/mcs/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
