version: '3.9'
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/config/prometheus.yaml"
    volumes:
      - /opt/docker/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    container_name: prometheus-pve-exporter
    volumes:
      - /opt/docker/pve.yml:/etc/prometheus/pve.yml
    ports:
      - "9221:9221"
    restart: unless-stopped
